import { motion, useMotionValue, useSpring, useTransform, useMotionTemplate } from "framer-motion";
import { Brain, Gauge, LineChart, Sparkles, Target, TrendingUp } from "lucide-react";
import type { LucideIcon } from "lucide-react";
import { memo, useCallback, useRef } from "react";
import type { MouseEvent, ReactNode } from "react";

const features: {
  icon: LucideIcon;
  title: string;
  desc: string;
  accent: string;
}[] = [
  {
    icon: Brain,
    title: "AI Planner",
    desc: "Your day, autogenerated. Adaptive schedules that learn what actually gets done.",
    accent: "from-blue-500 to-blue-400",
  },
  {
    icon: Gauge,
    title: "Discipline Score",
    desc: "A single number that captures consistency — updated in real time, honest with you.",
    accent: "from-cyan-500 to-blue-500",
  },
  {
    icon: Target,
    title: "Habit Tracking",
    desc: "Streaks, systems, and smart nudges. Zero friction to log — everything auto-syncs.",
    accent: "from-blue-600 to-cyan-400",
  },
  {
    icon: LineChart,
    title: "Analytics",
    desc: "Weekly reports that reveal patterns you'd never see manually. Beautiful, deep, actionable.",
    accent: "from-blue-400 to-blue-600",
  },
  {
    icon: Sparkles,
    title: "AI Coach",
    desc: "Chat with a coach trained on your data. It knows your peaks, dips, and blind spots.",
    accent: "from-cyan-400 to-blue-500",
  },
  {
    icon: TrendingUp,
    title: "Future Predictions",
    desc: "See the 90-day projection of your habits. Small changes → compound outcomes.",
    accent: "from-blue-500 to-cyan-500",
  },
];

export const Features = memo(function Features() {
  return (
    <section id="features" className="relative py-32 md:py-44 z-10">
      <div className="mx-auto max-w-6xl px-6">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, margin: "-100px" }}
          transition={{ duration: 0.5 }}
          className="max-w-2xl mb-16 motion-gpu"
        >
          <div className="text-[13px] font-medium tracking-wide text-blue-400 mb-4 flex items-center gap-2">
            <div className="w-2 h-2 rounded-full bg-blue-500 animate-pulse" />
            CAPABILITIES
          </div>
          <h2 className="text-4xl md:text-5xl lg:text-6xl font-medium tracking-tight leading-[1.1]">
            Every tool you need to stay
            <span className="text-muted-foreground"> relentlessly consistent.</span>
          </h2>
        </motion.div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5 md:gap-6">
          {features.map((f, i) => (
            <TiltCard key={f.title} index={i}>
              <div className="relative h-full glass rounded-[1.5rem] p-7 overflow-hidden group hover:bg-white/[0.04] transition-colors duration-500 border-white/5 hover:border-white/10 shadow-elevated">
                <div className="relative z-10" style={{ transform: "translateZ(30px)" }}>
                  <div
                    className={`w-12 h-12 rounded-xl bg-gradient-to-br ${f.accent} p-[1.5px] mb-6 shadow-lg shadow-blue-500/10 group-hover:scale-110 transition-transform duration-500`}
                  >
                    <div className="w-full h-full rounded-[10px] bg-background/90 backdrop-blur flex items-center justify-center">
                      <f.icon className="w-5 h-5 text-white" strokeWidth={1.5} />
                    </div>
                  </div>
                  <h3 className="text-xl font-medium tracking-tight text-white mb-3">{f.title}</h3>
                  <p className="text-sm text-muted-foreground leading-relaxed font-light">
                    {f.desc}
                  </p>
                </div>
              </div>
            </TiltCard>
          ))}
        </div>
      </div>
    </section>
  );
});

const TiltCard = memo(function TiltCard({
  children,
  index,
}: {
  children: ReactNode;
  index: number;
}) {
  const mx = useMotionValue(0);
  const my = useMotionValue(0);
  const mouseX = useMotionValue(0);
  const mouseY = useMotionValue(0);
  const boundsRef = useRef<DOMRect | null>(null);

  const rx = useSpring(useTransform(my, [-0.5, 0.5], [8, -8]), { stiffness: 100, damping: 20 });
  const ry = useSpring(useTransform(mx, [-0.5, 0.5], [-8, 8]), { stiffness: 100, damping: 20 });

  const onEnter = useCallback((e: MouseEvent<HTMLDivElement>) => {
    boundsRef.current = e.currentTarget.getBoundingClientRect();
  }, []);

  const onMove = useCallback(
    (e: MouseEvent<HTMLDivElement>) => {
      const r = boundsRef.current;
      if (!r) return;
      mx.set((e.clientX - r.left) / r.width - 0.5);
      my.set((e.clientY - r.top) / r.height - 0.5);
      mouseX.set(e.clientX - r.left);
      mouseY.set(e.clientY - r.top);
    },
    [mouseX, mouseY, mx, my],
  );

  const onLeave = useCallback(() => {
    boundsRef.current = null;
    mx.set(0);
    my.set(0);
    mouseX.set(-1000);
    mouseY.set(-1000);
  }, [mouseX, mouseY, mx, my]);

  const background = useMotionTemplate`radial-gradient(400px circle at ${mouseX}px ${mouseY}px, rgba(59, 130, 246, 0.15), transparent 80%)`;

  return (
    <motion.div
      initial={{ opacity: 0, y: 30 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true, margin: "-80px" }}
      transition={{ duration: 0.5, delay: index * 0.06, ease: [0.16, 1, 0.3, 1] }}
      onMouseEnter={onEnter}
      onMouseMove={onMove}
      onMouseLeave={onLeave}
      style={{ rotateX: rx, rotateY: ry, transformStyle: "preserve-3d", perspective: 1200 }}
      className="motion-gpu h-full relative group rounded-[1.5rem]"
    >
      <motion.div
        className="absolute inset-0 z-0 pointer-events-none rounded-[1.5rem] opacity-0 group-hover:opacity-100 transition-opacity duration-500"
        style={{ background }}
      />
      {children}
    </motion.div>
  );
});
